Repository Vdauphin/HeartsAndMinds, pull requests merged in 2019-04, with the labels that each got.

#658 FIX: Case conditions for static spawn
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
Labels: bug

#659 Add: Header comments to functions
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/handledisconnect.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/suicider.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_init.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_killed.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/belt.sqf
Labels: enhancement

#622 Add: Improve code syntaxe
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/find_pos.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/dlg.hpp
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/hd_hideout.sqf
Labels: enhancement

#608 Add: RemoteExecCall
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/garage.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/cache/hd_cache.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/delete.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/final_phase.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/set_groupowner.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/delete.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/request_delete.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/request_save.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/deaf/earringing.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/CuratorObjectPlaced.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/leaflets.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/player_respawn.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/treatment.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_killed.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/dismantle.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/boom.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/suicider_active.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/cache.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/give_intel.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/has_intel.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/search_for_intel.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/orders.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/tow.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/unhook.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/hd_hideout.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/unit_killed.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/hh.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/abort.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/get_city.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/underwater_generator.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/vehicle.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/set_done.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/init_headless.sqf
Labels: enhancement

#660 FIX: btc_player_side error when side mission cycle is activated
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
Labels: bug

#670 FIX: Disable wreck system on Helo vehicles
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/repair_wreck.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: bug

#630 Add: Direction to FOB
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/fob/create_s.sqf
Labels: DB conflict, enhancement
