Repository Vdauphin/HeartsAndMinds, pull requests merged in 2019-08, with the labels that each got.

#737 FIX: Towing for HEMTT flat
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/tow.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/unhook.sqf
Labels: bug

#736 Add: Vehicle in vehicle for towing when available
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/tow.sqf
Labels: enhancement

#723 FIX: Broken database when switching mission parameter: battle on sea
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/trigger_player_side.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/final_phase.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
Labels: DB conflict, bug, enhancement

#739 FIX: Description in capture officer mission
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: bug

#701 Add: Filter object by parent in mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
Labels: enhancement

#742 Add: Handcuff step for capture officer
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/setDescription.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: enhancement

#740 FIX: Remove unncessary format
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/setDescription.sqf
Labels: bug

#744 Add: Missing translation German
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: enhancement

#745 Add: Improve doc vehicles and logistic
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: enhancement

#743 Add: ED-1 support for IED
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/ied/checkLoop.sqf
Labels: enhancement

#741 Add: Side mission assassinate
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/setDescription.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/task/tasktypes.hpp
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
  README.md
Labels: enhancement

#746 Add: btc_fnc_typeOfPreview
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/typeOfPreview.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
Labels: enhancement

#750 FIX: Can select null city
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/usefulCity.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/checkpoint.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/civtreatment_boat.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/get_city.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hack.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/hostage.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/kill.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/mines.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/rescue.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/supply.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/tower.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/underwater_generator.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/vehicle.sqf
Labels: bug

#747 FIX: Don't add BTC Place interaction when ACE Carrying interaction is available
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: bug

#749 Add: Contact asset to hideout
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_hideout_composition.sqf
Labels: enhancement

#753 FIX: Enemy doesn't spawn inside the city radius
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/init.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
Labels: bug

#748 Add: Set and get vehicle properties function
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/getVehProperties.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/setVehProperties.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_respawn.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/server_repair_wreck.sqf
Labels: enhancement

#754 Update stringtable.xml: Add Simplified Chinese translation to new contents
  =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: bug

#761 FIX: RopeCreate fail return objtNull
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/lift_hook.sqf
Labels: bug

#758 Fix: Wrong localized string in stringtable.xml
  =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: bug

#763 Add: Use BI string for delete database
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/ask_reputation.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
  docs/InGame-documentation.md
Labels: enhancement

#762 FIX: missing mount FOB interaction
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
Labels: bug

#734 Add: Path information
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/path.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
Labels: enhancement
