Repository Vdauphin/HeartsAndMinds, pull requests merged in 2020-08, with the labels that each got.

#926 Add: Improve activation.sqf syntax
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
Labels: enhancement

#934 FIX: Patrol and traffic not deleted when player too far
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/create_patrol.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_patrol.sqf
Labels: bug

#937 Simplified Chinese Translation for #919 and #927
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: enhancement

#938 Add: Waypoint Timeout and completion radius persistant
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/addWP.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/evacuate.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/common/house_addWP.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/get_group.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/addWP.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/addWP.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/capture_officer.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/side/convoy.sqf
Labels: bug, enhancement

#931 Add: Use CBA eh for chemical propagation
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/add_veh.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createVehicle.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/veh_add_respawn.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createVehicle.sqf
Labels: enhancement

#939 FIX: AI get stuck by each other
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/patrol/addWP.sqf
Labels: bug

#941 FIX: Comment about btc_type_crewmen is a string not an array
  .github/release-drafter.yml
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/create.sqf
Labels: bug

#942 FIX: Error of reputation notify
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/change.sqf
Labels: bug

#950 FIX: isNull group error
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/data/spawn_group.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/send.sqf
Labels: bug
