Repository Vdauphin/HeartsAndMinds, pull requests merged in 2021-05, with the labels that each got.

#1076 Add: Selectable reputation notification level change
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/change.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: enhancement

#1067 Add: Disable some door in city when reputation is under high
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/doc.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/arsenal/loadout.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/getHouses.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/door/break.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/door/broke.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/door/lock.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
  README.md
  docs/InGame-documentation.md
Labels: enhancement

#1066 Add: Random physique intel in houses
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/param.hpp
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/de_activate.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/createIntels.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/info/has_intel.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
  docs/InGame-documentation.md
Labels: enhancement

#1093 FIX: City door are not locked when game has been saved
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
Labels: bug

#1094 Add: Chinesesimp translations for PR #957, #1066, #1067 and #1076
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: enhancement

#1087 Add: Delay find position outside rock
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/activate.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/city/findPos.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/civ/populate.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createUnit.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/delay/createVehicle.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/createUnits.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/create_group.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/mil/getBuilding.sqf
Labels: enhancement

#1097 FIX: For server using -autoinit, objects in container are not loaded after restart
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadcargo.sqf
Labels: bug

#1069 Add: Give food increase your reputation, removing food reduce reputation
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/headless.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/server.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/add_actions.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/int/foodGive.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/foodRemoved.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
  README.md
  docs/InGame-documentation.md
Labels: enhancement

#1100 Add: Simplified Chinese translation for #1069
  =BTC=co@30_Hearts_and_Minds.Altis/stringtable.xml
Labels: enhancement

#1065 Add: Fully save inventory in cargo (backpack content, weapon attachment)
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/compile.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadObjectStatus.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/load_old.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/loadcargo.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/save.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/db/saveObjectStatus.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/createVehicle.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/inventoryGet.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/inventorySet.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/setCargo.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/veh/respawn.sqf
  =BTC=co@30_Hearts_and_Minds.Altis/core/init_server.sqf
Labels: DB conflict, enhancement

#1101 FIX: Wrong format for empty inventory
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/log/create_apply.sqf
Labels: bug

#1102 FIX: Missing compileScript
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/eh/xeh_PreInit_EH.hpp
Labels: bug

#1106 FIX: Militia can spawn inside hideout when player is near it
  =BTC=co@30_Hearts_and_Minds.Altis/core/fnc/rep/call_militia.sqf
Labels: bug

#1107 FIX: btc_hideouts is undefine when no hideout
  =BTC=co@30_Hearts_and_Minds.Altis/core/def/mission.sqf
Labels: bug
